package com.flosy.core.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.flosy.core.database.dao.UserProfileDao
import com.flosy.core.database.entity.UserProfileEntity

/**
 * Main Room database for the Flosy app.
 *
 * This database stores all local data including user profile,
 * expenses, fixed expenses, and categories.
 *
 * Uses Room 2.7.1 with KMP support via BundledSQLiteDriver.
 *
 * @see UserProfileEntity for user profile storage
 */
@Database(
    entities = [UserProfileEntity::class],
    version = 1,
    exportSchema = true
)
@ConstructedBy(FlosynDatabaseConstructor::class)
abstract class FlosynDatabase : RoomDatabase() {

    /**
     * Access the UserProfile DAO for profile operations.
     */
    abstract fun userProfileDao(): UserProfileDao

    companion object {
        const val DATABASE_NAME = "flosy.db"
    }
}

/**
 * Room database constructor for KMP support.
 *
 * This expect object is required for Room to work in Kotlin Multiplatform.
 * The actual implementations are auto-generated by KSP for each platform.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object FlosynDatabaseConstructor : RoomDatabaseConstructor<FlosynDatabase> {
    override fun initialize(): FlosynDatabase
}
